### ISSUE TITLE
[Enhancement]: Animation adjustment

### ISSUE THREAD

**Issue by Abizrh** [Abizrh/beastie.nvim#7]
Add an option to select specific animation
- animation: `random` | `cursor`

`random` : beastie will appeared in random places
`cursor`    : beastie will follow wherever the cursor is

**Comment by Aliqyan-21** [comment]
Hey @Abizrh can I work on it? I would like to know you want these options to be added in user config (`config.lua`) right like animation = "random"/"cursor" ?

**Comment by Abizrh** [comment]
> Hey @Abizrh can I work on it? I would like to know you want these options to be added in user config (config.lua) right like animation = "random"/"cursor" ?

Yes absolutely, but after adding animation it should be changed to the current animation because,  as for now it just randomly appeared in the buffer.

**Comment by Aliqyan-21** [comment]
Can you elaborate, like in cursor animation type you want to 'spawn' the emoji near or around the cursor and then it should go back to it's normal animation right?

**Comment by Aliqyan-21** [comment]
**Suggestion** : How about we make the beastie follow the cursor in 'cursor' animation type?

**Comment by Abizrh** [comment]
> Suggestion : How about we make the beastie follow the cursor in 'cursor' animation type?

This is what I mean

**Comment by Aliqyan-21** [comment]
Ok @Abizrh I'm on it!
